/*
 *  Copyright (C) 2002-2026 RicardoRamosWorks.com and The DOSBox Team
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#if C_OPENGL

static const char advinterp2x_glsl[] =
    "varying vec2 v_texCoord;\n"
    "uniform sampler2D rubyTexture;\n"
    "uniform vec2 rubyInputSize;\n"
    "uniform vec2 rubyOutputSize;\n"
    "uniform vec2 rubyTextureSize;\n"
    ""
    "#if defined(VERTEX)\n"
    "attribute vec4 a_position;\n"
    ""
    "void main() {\n"
    "  gl_Position = a_position;\n"
    "  v_texCoord = vec2(a_position.x+1.0,1.0-a_position.y)*rubyInputSize;\n"
    "}\n"
    ""
    "#elif defined(FRAGMENT)\n"
    ""
    "vec3 getadvinterp2xtexel(vec2 coord) {\n"
    "	vec2 base = floor(coord/vec2(2.0))+vec2(0.5);\n"
    "	vec3 c4 = texture2D(rubyTexture, base/rubyTextureSize).xyz;\n"
    "	vec3 c1 = texture2D(rubyTexture, (base-vec2(0.0,1.0))/rubyTextureSize).xyz;\n"
    "	vec3 c7 = texture2D(rubyTexture, (base+vec2(0.0,1.0))/rubyTextureSize).xyz;\n"
    "	vec3 c3 = texture2D(rubyTexture, (base-vec2(1.0,0.0))/rubyTextureSize).xyz;\n"
    "	vec3 c5 = texture2D(rubyTexture, (base+vec2(1.0,0.0))/rubyTextureSize).xyz;\n"
    ""
    "	bool outer = c1 != c7 && c3 != c5;\n"
    "	bool c3c1 = outer && c3==c1;\n"
    "	bool c1c5 = outer && c1==c5;\n"
    "	bool c3c7 = outer && c3==c7;\n"
    "	bool c7c5 = outer && c7==c5;\n"
    ""
    "	vec3 l00 = mix(c3,c4,c3c1?3.0/8.0:1.0);\n"
    "	vec3 l01 = mix(c5,c4,c1c5?3.0/8.0:1.0);\n"
    "	vec3 l10 = mix(c3,c4,c3c7?3.0/8.0:1.0);\n"
    "	vec3 l11 = mix(c5,c4,c7c5?3.0/8.0:1.0);\n"
    ""
    "	coord = max(floor(mod(coord, 2.0)), 0.0);\n"
    "	/* 2x2 output:\n"
    "	 *    |x=0|x=1\n"
    "	 * y=0|l00|l01\n"
    "	 * y=1|l10|l11\n"
    "	 */\n"
    ""
    "	return mix(mix(l00,l01,coord.x), mix(l10,l11,coord.x), coord.y);\n"
    "}\n"
    ""
    "void main()\n"
    "{\n"
    "	vec2 coord = v_texCoord;\n"
    "#if defined(OPENGLNB)\n"
    "	gl_FragColor = getadvinterp2xtexel(coord);\n"
    "#else\n"
    "	coord -= 0.5;\n"
    "	vec3 c0 = getadvinterp2xtexel(coord);\n"
    "	vec3 c1 = getadvinterp2xtexel(coord+vec2(1.0,0.0));\n"
    "	vec3 c2 = getadvinterp2xtexel(coord+vec2(0.0,1.0));\n"
    "	vec3 c3 = getadvinterp2xtexel(coord+vec2(1.0));\n"
    ""
    "	coord = fract(max(coord,0.0));\n"
    "	gl_FragColor = vec4(mix(mix(c0,c1,coord.x), mix(c2,c3,coord.x), coord.y), 1.0);\n"
    "#endif\n"
    "}\n"
    "#endif";



static const char advmame2x_glsl[] =
    "varying vec2 v_texCoord;\n"
    "uniform sampler2D rubyTexture;\n"
    "uniform vec2 rubyInputSize;\n"
    "uniform vec2 rubyOutputSize;\n"
    "uniform vec2 rubyTextureSize;\n"
    ""
    "#if defined(VERTEX)\n"
    "attribute vec4 a_position;\n"
    ""
    "void main() {\n"
    "  gl_Position = a_position;\n"
    "  v_texCoord = vec2(a_position.x+1.0,1.0-a_position.y)*rubyInputSize;\n"
    "}\n"
    ""
    "#elif defined(FRAGMENT)\n"
    ""
    "vec3 getadvmame2xtexel(vec2 coord) {\n"
    "	vec2 base = floor(coord/vec2(2.0))+vec2(0.5);\n"
    "	vec3 c4 = texture2D(rubyTexture, base/rubyTextureSize).xyz;\n"
    "	vec3 c1 = texture2D(rubyTexture, (base-vec2(0.0,1.0))/rubyTextureSize).xyz;\n"
    "	vec3 c7 = texture2D(rubyTexture, (base+vec2(0.0,1.0))/rubyTextureSize).xyz;\n"
    "	vec3 c3 = texture2D(rubyTexture, (base-vec2(1.0,0.0))/rubyTextureSize).xyz;\n"
    "	vec3 c5 = texture2D(rubyTexture, (base+vec2(1.0,0.0))/rubyTextureSize).xyz;\n"
    ""
    "	bool outer = c1 != c7 && c3 != c5;\n"
    "	bool c3c1 = outer && c3==c1;\n"
    "	bool c1c5 = outer && c1==c5;\n"
    "	bool c3c7 = outer && c3==c7;\n"
    "	bool c7c5 = outer && c7==c5;\n"
    ""
    "	vec3 l00 = mix(c4,c3,c3c1?1.0:0.0);\n"
    "	vec3 l01 = mix(c4,c5,c1c5?1.0:0.0);\n"
    "	vec3 l10 = mix(c4,c3,c3c7?1.0:0.0);\n"
    "	vec3 l11 = mix(c4,c5,c7c5?1.0:0.0);\n"
    ""
    "	coord = max(floor(mod(coord, 2.0)), 0.0);\n"
    "	/* 2x2 output:\n"
    "	 *    |x=0|x=1\n"
    "	 * y=0|l00|l01\n"
    "	 * y=1|l10|l11\n"
    "	 */\n"
    ""
    "	return mix(mix(l00,l01,coord.x), mix(l10,l11,coord.x), coord.y);\n"
    "}\n"
    ""
    "void main()\n"
    "{\n"
    "	vec2 coord = v_texCoord;\n"
    "#if defined(OPENGLNB)\n"
    "	gl_FragColor = getadvmame2xtexel(coord);\n"
    "#else\n"
    "	coord -= 0.5;\n"
    "	vec3 c0 = getadvmame2xtexel(coord);\n"
    "	vec3 c1 = getadvmame2xtexel(coord+vec2(1.0,0.0));\n"
    "	vec3 c2 = getadvmame2xtexel(coord+vec2(0.0,1.0));\n"
    "	vec3 c3 = getadvmame2xtexel(coord+vec2(1.0));\n"
    ""
    "	coord = fract(max(coord,0.0));\n"
    "	gl_FragColor = vec4(mix(mix(c0,c1,coord.x), mix(c2,c3,coord.x), coord.y), 1.0);\n"
    "#endif\n"
    "}\n"
    "#endif";



static const char rgb2x_glsl[] =
    "varying vec2 v_texCoord;\n"
    "uniform sampler2D rubyTexture;\n"
    "uniform vec2 rubyInputSize;\n"
    "uniform vec2 rubyOutputSize;\n"
    "uniform vec2 rubyTextureSize;\n"
    ""
    "#if defined(VERTEX)\n"
    "attribute vec4 a_position;\n"
    ""
    "void main() {\n"
    "  gl_Position = a_position;\n"
    "  v_texCoord = vec2(a_position.x+1.0,1.0-a_position.y)/2.0*rubyInputSize * 2.0;\n"
    "}\n"
    ""
    "#elif defined(FRAGMENT)\n"
    ""
    "vec4 getRGB2xtexel(vec2 coord) {\n"
    "	vec2 mid = vec2(0.5);\n"
    "	vec4 s = texture2D(rubyTexture, (floor(coord/vec2(2.0))+mid)/rubyTextureSize);\n"
    ""
    "	coord = max(floor(mod(coord, 2.0)), 0.0);\n"
    "	/* 2x2 output:\n"
    "	 *    |x=0|x=1\n"
    "	 * y=0| r | g\n"
    "	 * y=1| b |rgb\n"
    "	 */\n"
    ""
    "	s.r *= 1.0 - abs(coord.x - coord.y);\n"
    "	s.g *= coord.x;\n"
    "	s.b *= coord.y;\n"
    "	return s;\n"
    "}\n"
    ""
    "void main()\n"
    "{\n"
    "	vec2 coord = v_texCoord;\n"
    "#if defined(OPENGLNB)\n"
    "	gl_FragColor = getRGB2xtexel(coord);\n"
    "#else\n"
    "	coord -= 0.5;\n"
    "	vec4 c0 = getRGB2xtexel(coord);\n"
    "	vec4 c1 = getRGB2xtexel(coord+vec2(1.0,0.0));\n"
    "	vec4 c2 = getRGB2xtexel(coord+vec2(0.0,1.0));\n"
    "	vec4 c3 = getRGB2xtexel(coord+vec2(1.0));\n"
    ""
    "	coord = fract(max(coord,0.0));\n"
    "	gl_FragColor = mix(mix(c0,c1,coord.x), mix(c2,c3,coord.x), coord.y);\n"
    "#endif\n"
    "}\n"
    "#endif";



static const char scan2x_glsl[] =
    "varying vec2 v_texCoord;\n"
    "uniform vec2 rubyInputSize;\n"
    "uniform vec2 rubyOutputSize;\n"
    "uniform vec2 rubyTextureSize;\n"
    ""
    "#if defined(VERTEX)\n"
    "attribute vec4 a_position;\n"
    "void main() {\n"
    "  gl_Position = a_position;\n"
    "  v_texCoord = vec2(a_position.x+1.0,1.0-a_position.y)/2.0*rubyInputSize;\n"
    "}\n"
    ""
    "#elif defined(FRAGMENT)\n"
    "uniform sampler2D rubyTexture;\n"
    ""
    "void main() {\n"
    "  vec2 prescale = vec2(2.0);\n"
    "  vec2 texel = v_texCoord;\n"
    "  vec2 texel_floored = floor(texel);\n"
    "  vec2 s = fract(texel);\n"
    "  vec2 region_range = vec2(0.5) - vec2(0.5) / prescale;\n"
    ""
    "  vec2 center_dist = s - vec2(0.5);\n"
    "  vec2 f = (center_dist - clamp(center_dist, -region_range, region_range)) * prescale + vec2(0.5);\n"
    ""
    "  vec2 mod_texel = min(texel_floored + f, rubyInputSize-0.5);\n"
    "  vec4 p = texture2D(rubyTexture, mod_texel/rubyTextureSize);\n"
    "  float ss = abs(s.y*2.0-1.0);\n"
    "  p -= p*ss;\n"
    ""
    "  gl_FragColor = p;\n"
    "}\n"
    "#endif";



static const char tv2x_glsl[] =
    "varying vec2 v_texCoord;\n"
    "uniform vec2 rubyInputSize;\n"
    "uniform vec2 rubyOutputSize;\n"
    "uniform vec2 rubyTextureSize;\n"
    ""
    "#if defined(VERTEX)\n"
    "attribute vec4 a_position;\n"
    "void main() {\n"
    "  gl_Position = a_position;\n"
    "  v_texCoord = vec2(a_position.x+1.0,1.0-a_position.y)/2.0*rubyInputSize;\n"
    "}\n"
    ""
    "#elif defined(FRAGMENT)\n"
    "uniform sampler2D rubyTexture;\n"
    ""
    "void main() {\n"
    "  vec2 prescale = vec2(2.0);\n"
    "  vec2 texel = v_texCoord;\n"
    "  vec2 texel_floored = floor(texel);\n"
    "  vec2 s = fract(texel);\n"
    "  vec2 region_range = vec2(0.5) - vec2(0.5) / prescale;\n"
    ""
    "  vec2 center_dist = s - 0.5;\n"
    "  vec2 f = (center_dist - clamp(center_dist, -region_range, region_range)) * prescale + vec2(0.5);\n"
    ""
    "  vec2 mod_texel = min(texel_floored + f, rubyInputSize-0.5);\n"
    "  vec4 p = texture2D(rubyTexture, mod_texel/rubyTextureSize);\n"
    "  float ss = abs(s.y*2.0-1.0);\n"
    "  p -= p*ss*3.0/8.0;\n"
    ""
    "  gl_FragColor = p;\n"
    "}\n"
    "#endif";



static const char sharp_glsl[] =
    "varying vec2 v_texCoord;\n"
    "uniform vec2 rubyInputSize;\n"
    "uniform vec2 rubyOutputSize;\n"
    "uniform vec2 rubyTextureSize;\n"
    "varying vec2 prescale; // const set by vertex shader\n"
    ""
    "#if defined(VERTEX)\n"
    "attribute vec4 a_position;\n"
    "void main() {\n"
    "  gl_Position = a_position;\n"
    "  v_texCoord = vec2(a_position.x+1.0,1.0-a_position.y)/2.0*rubyInputSize;\n"
    "  prescale = ceil(rubyOutputSize / rubyInputSize);\n"
    "}\n"
    ""
    "#elif defined(FRAGMENT)\n"
    "uniform sampler2D rubyTexture;\n"
    ""
    "void main() {\n"
    "  const vec2 halfp = vec2(0.5);\n"
    "  vec2 texel_floored = floor(v_texCoord);\n"
    "  vec2 s = fract(v_texCoord);\n"
    "  vec2 region_range = halfp - halfp / prescale;\n"
    ""
    "  vec2 center_dist = s - halfp;\n"
    "  vec2 f = (center_dist - clamp(center_dist, -region_range, region_range)) * prescale + halfp;\n"
    ""
    "  vec2 mod_texel = min(texel_floored + f, rubyInputSize-halfp);\n"
    "  gl_FragColor = texture2D(rubyTexture, mod_texel / rubyTextureSize);\n"
    "}\n"
    "#endif";


#endif

